config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create]
  resources :registrations, only: [:create]
  resources :players, only: %i[index show create update destroy delete]
  delete :players, to: 'players#delete'
  delete :logout, to: 'sessions#logout'
  get :logged_in, to: 'sessions#logged_in'
  root to: 'static#root'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
    extend ActiveSupport::Concern
    
    included do
        before_action :set_current_user
    end
    
    def set_current_user
        if session[:user_id]
        @current_user = User.find(session[:user_id])
        end
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[show edit update destroy]

  # GET /players or /players.json
  def index
    @players = Player.all.where(user_id: params[:user_id])
    render json: @players
  end

  # GET /players/1 or /players/1.json
  def show; end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit; end

  # POST /players or /players.json
  def user_has_more_than_20_players
    Player.all.where(user_id: player_params[:user_id]).count >= 20
  end

  def user_already_has_player
    Player.all.where(user_id: params[:user_id], player_id: player_params[:player_id]).count.positive?
  end

  def create
    return redirect_to players_path, notice: 'You already have this player.' if user_already_has_player
    return redirect_to players_path, notice: "You can't have more than 20 players." if user_has_more_than_20_players

    @player = Player.new(player_params)

    if @player.save
      render :new, status: :created
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  # def destroy
  #   player = Player.find(params[:player_id])
  #   player.destroy
  #   respond_to do |format|
  #     format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  def delete
    player = Player.all
    player_to_destroy = player.where(player_id: params[:player_id], user_id: params[:user_id])
    if player_to_destroy.empty?
      render json: { error: 'Unable to delete player' }, status: 400
    else
      player_to_destroy.destroy_all
      render json: { message: 'Player successfully deleted' }, status: 200
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def player_params
    params.require(:player).permit(:user, :user_id, :player_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def create
        user = User.create!(
            email: params['user']['email'],
            password: params['user']['password'],
            password_confirmation: params['user']['password_confirmation']
        )
        if user
            session[:user_id] = user.id
            render json: {
                status: :created,
                user: user
            }
        else
            render json: { status: 500 }
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    # def create
    #     @user = User.find_by_credentials(
    #         params[:user][:username],
    #         params[:user][:password]
    #     )
    #     if @user
    #         login!(@user)
    #         render 'api/users/show'
    #     else
    #         render json: ["Invalid username or password"], status: 401
    #     end
    # end
    include CurrentUserConcern
    def create
        user = User
            .find_by(email: params["user"]["email"])
            .try(:authenticate, params["user"]["password"])
        if user
            session[:user_id] = user.id
            render json: {
                status: :created,
                logged_in: true,
                user: user
            }
        else
            render json: { status: 401 }
        end
    end

    def logged_in
        if @current_user
            render json: {
                logged_in: true,
                user: @current_user
            }
        else
            render json: {
                logged_in: false
            }
        end
    end
    def logout
        session.delete(:user_id)
        render json: { status: 200, logged_out: true }
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def root
    #  render json: { status: "Hello from static controller" }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NhlApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :player_id %>
    <%= form.text_field :player_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.user %></td>
        <td><%= player.user_id %></td>
        <td><%= player.player_id %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @player.user %>
</p>

<p>
  <strong>User:</strong>
  <%= @player.user_id %>
</p>

<p>
  <strong>Player:</strong>
  <%= @player.player_id %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>